### PR TITLE
Automatically configure environment for CfEnv

### LINKED ISSUE #344: Auto Configure manifest for Spring boot apps with `java-cfenv` dependencies
Depends on #343 . Spring Boot apps deployed to CloudFoundry that are autoconfigured with `java-cfenv` must set environment variables in the manifest. Otherwise cfenv will throw an exception:

`JBP_CONFIG_SPRING_AUTO_RECONFIGURATION='{enabled:false}`
`SPRING_PROFILES_ACTIVE=cloud`

It is possible to use Spring Boot `JarFileArchive` along with `URLClassLoader` to inspect the boot jar and determine if it contains `CfEnv.class` . If it's there, we add the required configuration automatically. 

The limitation is that this will only work for boot apps.  In theory it's possible to do something similar for docker images, but would require a docker daemon accessible to the deployer host/container. So does not seem practical.  Obviously, this will not work the same for non-boot jars.  But it should cover the vast majority of cases,  including the `Fahrenheit` release of Spring supported stream applications.

### PR DESCRIPTION
**Pull request by dturanski**
Resolves #344 

Updated PR since @ilayaperumalg first reviewed it.  

This adds `CfEnfAwareResource` and clones the immutable `AppDeploymentRequest` as `CfEnvAwareApplicationDeploymentRequest` to contain the CfEnvAwareResource.  The app deployer and task launcher do the conversion first in `deploy` and `launch` respectively.  

`CfEnvAwareResource` determines if it includes `CfEnv.class` at creation time and sets its `hasCfEnv` property.  This only applies to boot jars,  e.g. Docker images are not inspected as it would require a docker daemon to inspect the image.  
If CfEnv is present, the deployer will:

 * disable auto-reconfiguration in the Java build pack
 * activate the cloud profile if it is not already declared active in any external property source (environment variable, application properties, or command line args) 
* if any of these contains a property key that binds to `spring.profiles.active` and does not already include `cloud`, `cloud` will be appended.  
* if `spring.profiles.active` is not declared it will add it as an application property (in `SPRING_APPLICATION_JSON` by default). 

NOTE: This will be convenient for users of upcoming releases of supported stream-applications, since they all use `java-cfenv` and will fail on cloud foundry without this configuration.  At some future time the Java build pack may incorporate `java-cfenv` to make this obsolete.  CNB buildpacks will include similar features, although via an new service binding configuration standard that does not use `VCAP_SERVICES`.

### CODE REVIEW

File: src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvConfigurer.java [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+		}
+		catch (IOException e) {
+			throw new IllegalArgumentException(e.getMessage(), e);
+		}
+
+		Map<String, String> updatedEnvironment = new HashMap<>(environment);
+
+		if (CfEnvResolver.hasCfEnv(resource)) {
+			updatedEnvironment.putIfAbsent(JBP_CONFIG_SPRING_AUTO_RECONFIGURATION, ENABLED_FALSE);
+			if (appendToExistingEntry(updatedEnvironment, SPRING_PROFILES_ACTIVE, CLOUD_PROFILE_NAME)) {
```
Comment (ilayaperumalg) [inline src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvConfigurer.java:62]: I wonder if we need to check all possible `RelaxedNames` when updating this entry.

Comment (dturanski) [reply src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvConfigurer.java:62]: This is checking existing environment variables. I don't think I've ever seen env like springProfilesActive or spring-profiles-active.  If a user does this, they're on their own AFAIC.

Comment (dturanski) [reply src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvConfigurer.java:62]: It's also possible to override the spring profiles with properties that go to SAJ, or command line args in task apps.  Maybe a better way to update the profile is is at the highest level of precedence instead of env vars.

File: src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvAwareResource.java [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+
+			try {
+				JarFileArchive archive = new JarFileArchive(app.getFile());
+				List<URL> urls = new ArrayList<>();
+				archive.getNestedArchives(entry -> entry.getName().endsWith(".jar")).forEach(a -> {
+					try {
+						urls.add(a.getUrl());
+					}
+					catch (MalformedURLException e) {
+						e.printStackTrace();
```
Comment (jvalkeal) [inline src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvAwareResource.java:140]: Log or throw.

**Comment by ilayaperumalg** [comment]
LGTM

**Comment by ilayaperumalg** [comment]
Merging.
